name: Autograding Tests and Code Review Assignment

on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run autograding tests (if applicable)
      # Uncomment and customize this section if you have autograding tests.
      # - name: Run tests
      #   uses: classroom-resources/autograding-io-grader@v1
      #   with:
      #     test-name: Addition Test
      #     id: addition-test
      #     command: "./bin/add.sh"
      #     input: 1 2
      #     expected-output: 3
      #     comparison-method: exact
      #     timeout: 10

      # Step 3: Report autograding results (if applicable)
      # Uncomment and customize this section if you are using autograding.
      # - name: Autograding Reporter
      #   uses: classroom-resources/autograding-grading-reporter@v1
      #   env:
      #     ADDITION-TEST_RESULTS: "${{ steps.addition-test.outputs.result }}"
      #   with:
      #     runners: addition-test

  
